---
#hbase to hive config

mapreduce:

  hadoopUserName: fl76
  hbaseSnapshotPrefix: fl76_test
  libPathLocal: target/lib
  libPathRemote: /user/fl76/lib
  # only for dev
  jobJar: target/mapreduce-hfile-0.0.1-SNAPSHOT.jar
  
hive: 

  jdbc: 
    driverClassName: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://10.16.238.79:10000/default
    username: fl76
    password: 
  table:
    outputPathRemote: /user/fl76/hive/
    partitionColumn: dt
    
tables:
  - hbaseTableName: ecitem:IM_ItemBase
    hiveTableName: IM_ItemBase
    maxSplitSize: 100
    reduceNumber: 100
    columns:
      - { columnFamily: "BaseInfo", qualifier: "ItemNumber", type: "string", hiveColumn: "ItemNumber" }
      - { columnFamily: "BaseInfo", qualifier: "ItemGroupID", type: "int", hiveColumn: "ItemGroupID" }